name: Refresh Feed (Second)
on:
  workflow_dispatch:
  schedule:
    - cron: 00 12 * * 0-6
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: 'dev' 
  
      - name: Fetch API Data ğŸ“¦
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://www.googleapis.com/youtube/v3/search?key=${{secrets.YOUTUBE_API_KEY}}&channelId=UCLIVVSFSj9kbYUJzGYIjiUg&part=snippet,id&order=date&maxResults=10
          CONFIGURATION: '{ "method": "GET" }'
          SAVE_NAME: youtube

      - name: Build and Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: dev
          folder: fetch-api-data-action
          target-folder: src/data
